# Industry standard port for Eureka Server
server.port=8761

# Tell Eureka not to register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Security credentials for the Eureka Dashboard and Client Registration
spring.security.user.name=eureka_admin
spring.security.user.password=eureka_password_123

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info