server.port=8084

eureka.client.serviceUrl.defaultZone=http://eureka_admin:eureka_password_123@localhost:8761/eureka/

spring.datasource.url=jdbc:mysql://localhost:3306/railway_schedule_db?updateTimeZone=true
spring.datasource.username=root
spring.datasource.password=#Root@66
spring.jpa.hibernate.ddl-auto=update

jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a7bd8e1db5c09e3e7f4116853a808f95

logging.file.name=logs/schedule-service.log
logging.level.com.railway=DEBUG

springdoc.api-docs.path=/api/schedules/v3/api-docs